### ISSUE TITLE
Settings does not keep the selected Preview Theme if Theme has Spaces in the Folder Name

### ISSUE THREAD

**Issue by SergeBxl** [RickStrahl/MarkdownMonster#1075] opened 2023-12-20 13:49 UTC
Hi
I updated MM to version 3.1.10 (registered version). The preview theme is the default Dharkan. I copied the Dharkan folder and its contents with a new name in the folder C:\Users\User\AppData\Local\Markdown Monster\PreviewThemes. When I try to select this "new" theme either from the dropdown in the bottom bar, or by typing the folder name in the Settings dialog (as explained in the Help), or even by editing the entry in C:\Users\User\AppData\Roaming\Markdown Monster\MarkdownMonster.json , the new theme is not selected. Dharkan is always coming back.
Any help is appreciated. And thanks for a great tool.

**Comment by jsquire** [comment] 2024-01-03 21:23
This is happening for me as well; I'm unable to change the theme.  When using the status bar menu, any choice is immediately reset to Darkhan if the preview window is open.  If not open, the selection can be made but is reset as soon as a preview is opened.

**Comment by RickStrahl** [comment] 2024-01-03 22:35
Previewthemes live in the install folder, not in the shared folder. So it:

`<installFolder>\PreviewThemes`

That determines what's available. You can copy and create new themes and they won't be affected by updates (unless you wipe the folder completely).

**Comment by RickStrahl** [comment] 2024-01-04 05:42
I've updated the documentation for Preview Theme Customization on the docs site:

[Switching and Customizing Preview Themes - Custom Themes](https://markdownmonster.west-wind.com/docs/_4nn17bfic.htm#theme-customization)

**Comment by RickStrahl** [comment] 2024-01-09 20:41
> This is happening for me as well; I'm unable to change the theme. When using the status bar menu, any choice is immediately reset to Darkhan if the preview window is open. If not open, the selection can be made but is reset as soon as a preview is opened.

I suspect that's happening because either the preview themes folder is not accessible or the folder that contains the selected theme doesn't exist in the **install directory**. (see docs)

If you're using a portable install you may have to tweak your permissions in order to be able to read and write at the location you saved the installation files.

**Comment by RickStrahl** [comment] 2024-01-11 02:03
Ok so

**Comment by RickStrahl** [comment] 2024-01-11 02:38
OK, turns out this is a regression bug that was trying to address spaces in the theme path, but in the process broke the directory validation. 

This should be fixed in 3.1.15.1

**Closed** 2024-01-12 19:21 UTC
Labels: bug
