### ISSUE TITLE
Grammarly support

### ISSUE THREAD

**Issue by Philippe91** [RickStrahl/MarkdownMonster#1008] opened 2023-02-11 14:46 UTC
Grammarly is everywhere these days. Eg. there is an excellent plugin to have Grammarly in Visual Studio Code. I wish Markdown Monster could have support for it too.

**Comment by RickStrahl** [comment] 2023-02-11 20:51
You've posted this before - it's a duplicate of #967 

And the answer is it can't be done in this editor. 

I took a quick look at the VS code integration and that integration is not really useful. Without the full UI support it's more or less pointless. 

The issue is that Grammarly closely controls where the tool is used and they want it used inside of the browser, preferrably on their Web site.

**Comment by RickStrahl** [comment] 2023-02-11 20:55
One thing that could potentially be done is to open the document on a regular browser page for you to do spell/grammar checking on and then allow pushing that back into MM somehow or maybe even in real time as you type. 

But even that IMHO would be hokey as hell.

**Comment by Philippe91** [comment] 2023-02-12 08:17
Sorry, I did not remember I posted this request before. As a non-English speaking person, a tool like Grammarly is beneficial. And recently, I was amazed by the number of AI writing assistant solutions (133 listed here: https://www.saasworthy.com/list/ai-writing-assistant-software). These types of AI tools could become the norm in the short future.

**Comment by RickStrahl** [comment] 2023-02-13 21:56
I agree - it would be super nice to have I just don't know of a way to make that work in this editor.

The only way integration into MM could work is to have some sort of grammar API that can be used to look things up, but there are only a few of those and they are very expensive and not meant for consumer use (ie. integrations). If supported it has to be something that the end user is signed up for (ie. like Grammarly).

**Closed** 2023-02-13 21:56 UTC
Labels: can't fix
