### ISSUE TITLE
Error on New File

### ISSUE THREAD

**Issue by Randy-Buchholz** [RickStrahl/MarkdownMonster#702] opened 2020-09-21 12:25 UTC
I occasionally encounter a problem when creating a new document.
When creating a document the document tab opens but throws an error, offering to debug. Selecting "no" loops and I must kill the process. If I debug I can sometimes get back into the app and kill the page, but not always. This will usually go away on reboot, but not always. I can't determine what causes it to start, but it seems to pop up soon after I attempt to paste by using `ctrl-v` instead of `ctrl-shift-v`. 

<img width="394" alt="Error" src="https://user-images.githubusercontent.com/30436777/93765761-09db5480-fbdb-11ea-8b86-35b96268bc8e.PNG">

<img width="766" alt="Debug" src="https://user-images.githubusercontent.com/30436777/93765768-0cd64500-fbdb-11ea-9149-4ddf43df87ac.PNG">

**Comment by RickStrahl** [comment] 2020-09-21 21:36
I have not seen this, neither myself or in the logs...

It looks like a timing issue - that code is firing before the document has initialized properly which is a bit odd. I think this could happen if you create a new document and immediately start typing perhaps before the document is actually visible in the editor. Any other hints?

This is an easy fix - that code just needs a check for the object's existence, but I'd like to track down what the root cause is.

**Comment by Randy-Buchholz** [comment] 2020-09-21 23:05
Hotkey, menu, and tool icons all do this once it starts happening. 
It happens before the doc is available to the user. The document tab and the message box show essentially together.
It's only happened a couple of times and it was moths between. I can't be sure but it seems that it occurs after I fat-finger some hot-key combination with keys on the left side of the keyboard. Sorry I can't give you more to go on. It does loop if that helps. Selecting "no" just closes and reopens the error.

**Comment by RickStrahl** [comment] 2020-09-30 06:40
Did you check the latest versions? This should be fixed.

**Closed** 2020-10-08 03:51 UTC
