### ISSUE TITLE
Can not close the evaluation alert pop up

### ISSUE THREAD

**Issue by ajit555** [RickStrahl/MarkdownMonster#403] opened 2018-07-14 08:00 UTC
I left the MM app open for some time, so the evaluation alert pop up opened. Now, I can not close it. 

![image](https://user-images.githubusercontent.com/194380/42722451-c95ac4d2-8769-11e8-98b1-605e04581051.png)

**Comment by RickStrahl** [comment] 2018-07-16 18:44
Hmmm... that shouldn't happen, but I can't duplicate it. I unregistered my copy and have been running with that for the last 2 days with MM left open for long periods of time. The dialog pops up at intervals which is as designed, but it also closes on either the X click or the **Register your Copy** click.

Any more notes and what might be different?

**Comment by RickStrahl** [comment] 2018-07-21 00:54
I'm going to close this since I can't repro and there's no further feedback.

**Closed by RickStrahl** 2018-07-21 00:54 UTC
Labels: cant duplicate

**Comment by ajit555** [comment] 2018-08-11 05:00
Sorry for no reply, I was on holiday.
