### ISSUE TITLE
Can't install WebView2 because it's already installed and now I am stuck

### ISSUE THREAD

**Issue by Tony20221** [RickStrahl/MarkdownMonster#1029] opened 2023-04-23 20:24 UTC
First, Norton blocks me from installing it because it thinks the installer is suspicious. So I have to recover it.
Then it blocks MM from downloading WebView2. I disable Norton for 15 minutes.

MM keeps saying 'The webview runtime is not installed' and tried to download. The WebView2 installer fails saying it's already installed.
I also downloaded the installer manually and the installer fails saying it's already installed.

Why does MM think it's not installed? I am running Windows 11. 
I ran MM on an older Windows 10 machine and it ALWAYS downloaded WebView2 regardless. It does this even if I just installed it a few seconds ago. So why detect if WebView2 is installed if the installer will always download and install it anyway??

So now I am stuck and can't install it. There should be a way to skip the WebView2 installation. Let it be my problem.

**Comment by RickStrahl** [comment] 2023-04-24 03:15
That sounds like the WebView install is borked and you probably need to uninstall and reinstall. I suspect there might also be another application using it so it's not actually updated.

As to the WebView installer, MM just launches the WebView Web installer - MM uses the native WebView installer binaries which is as 'safe' as we can make that install. That doesn't excuse the problems, but we have very little control over that process. If you have a failed install, the WebView install can get messed up and the best way is to completely uninstall it, and - ugh reboot, then reinstall. I suspect the install got borked when Norton blocked half way through.

There's nothing I can do about the AV issues unfortunately - binaries are signed and they get downloaded hundreds of times a day so there's lots of precedence. AV checks for Chocolatey and they do a AV scan - which haven't shown any actual virus false positive for a long time, so I think Norton is probably blocking purely on reputation and perhaps strict Windows install settings (SmartScreen which if enabled pretty much doesn't want to install anything that's not coming from the Store).

If you want to bypass all that, you can install the portable version. It won't install the WebView and doesn't run an install at all - just copy to the folder where you want it. 

More info here:

[Markdown Monster Portable Version](https://markdownmonster.west-wind.com/docs/_4t90rhfy9.htm)

Not sure how that'll work with Norton but I suppose you can add an exclusion if it still doesn't want to go.

+++ Rick ---

**Comment by Tony20221** [comment] 2023-04-24 07:33
I can't uninstall WebView. It gives me the option to repair or cancel. If I try to reinstall it, it says it's already installed. I have done the repair several times already and also rebooted. The portable version says webview is not installed and refuses to continue.
So I don't know why MM thinks there's no Webview installed. Webview is showing it's installed.

The point I made in my post is that MM always downloads the webview2 installer whether I have it installed or not. This was noticed on another machine which runs Windows 10. Why does MM just always download and install Webview even though I just installed MM. It blindly just reinstalls it every single time.  What if I want to keep a certain version of webview? Unless multiple versions can be installed side by side on the machine.

Also the silly Norton keeps blocking the download of Webview from within MM even though I disable the firewall and the AV. 

I am unable to use either versions of MM. 



![image](https://user-images.githubusercontent.com/99626433/233927709-ec1c2ed0-a2dc-469a-b85d-2111063772ff.png)

**Comment by HamedFathi** [comment] 2023-04-24 11:40
@RickStrahl 

It is not an Anti-virus issue (I have nothing), Same issue for me too so I had to back to an older version.

https://twitter.com/Hamed__Fathi/status/1650179087204229122

**Comment by Tony20221** [comment] 2023-04-24 17:12
@RickStrahl Maybe I should be concerned about MM downloading and installing WebView and possibly overwriting the one my machine already has. Maybe the one I have works just fine and there are other apps using it and MM puts a newer version which introduces new bugs and breaks existing apps. I know Teams uses WebView but I don' t know if it uses the system's one or its own isolated version. You've been complaining about WebView bugs for months, plus WebView used to work and then it doesn't anymore with a newer version,  so I am not keen about MM always wanting to download the latest version.  And not care about the version already installed? Also, it doesn't look like its WebView detection mechanism is very reliable.

**Comment by RickStrahl** [comment] 2023-04-24 19:34
@Hamed - WebView installs are **EverGreen**  meaning they are constantly updated by both applications and Windows. As said I use the standard WebView installer which installs the **latest EverGreen** version not a fixed or old version.

MM checks the WebView version so that it matches the latest version installed that matches .NET components. The .NET components are always deployed and keyed to a minimum WebView Runtime version and that's what MM checks. If an old version exists it'll prompt to update. If the runtime is in fact installed and you get that prompt most likely you have an older version installed (or some app installed after MM installed an older version).

As to the problem issues I've tweeted and posted about on my blog, they are not in the WebView Runtime, they are in the .NET Components which is private to the applications using them (ie. MM) and not shared across the machine.

Ultimately in order to run MM you need to have a recent version of the WebView Runtime installed. MM updates frequently so the Runtime is pretty much always expected to be the latest.

At the end of the day the math is simple: MM needs a WebView runtime. if the Runtime cannot be installed or the version is not current it's not going to run. 

MM is installed between 50-100 times a day and I've seen 2 or 3 complaints in the last 3 years.  Granted some may not be reported but if this was widespread I sure would have heard more about this.  I install MM several times a day for dev or release publishing so I'm pretty sure the process works.

I can't spend time chasing down people's AV software setups or other software installs that fail. If you think that the install is a problem I already suggested to use the portable install and bring your own **current** WebView install. 


FWIW I've asked the WebView time on a number of occasions to fix the WebView installer to not reinstall the runtime if it's already installed. Unfortunately their installer will **always** reinstall the runtime even if you already have the latest version. Here's the issue I filed at the time. 

https://github.com/MicrosoftEdge/WebView2Feedback/issues/1821

It's still open and was never addressed.

**Comment by RickStrahl** [comment] 2023-04-24 19:40
@Tony20221 If you can't uninstall the WebView there's some other app that's holding that install hostage. And that's likely what the problem is: The version is likely locked and can't be updated unless the other app updates or removes it. Since that is likely outdated, that's also likely why MM keeps reinstalling and (if whatever uses it is running) and failing to re-install.

Check the dependencies of the WebView install and see what applications depend on it and you likely find your culprit. At minimum you can try shutting down whatever app it is then try reinstalling (either MM or the WebView Runtime installer).

**Comment by RickStrahl** [comment] 2023-04-24 19:43
In the meantime I'm going to grab the latest WebView Runtime setup in case Microsoft changed something there that might have issues, but I don't think so since the install is actually running and explicitly failing.

To be clear MM ships the actual MS installer which is what it executes during install as an external executable:

![image](https://user-images.githubusercontent.com/1374013/234099423-9769e897-ff0e-4b79-b29e-596e03cce22f.png)

**Comment by RickStrahl** [comment] 2023-04-24 21:06
Just to be clear the latest version of the WebView that should work (as of 04/24/2023):

![image](https://user-images.githubusercontent.com/1374013/234114385-65185a01-4448-41da-8920-aa10dc8f75c8.png)

And @Tony20221 I'm sorry - I see actually the same thing as you that the WebView can't be uninstalled any longer. Apparently Microsoft has now made it a system component in one of the recent Windows 11 updates and it auto-updates it looks like. 

That's actually good to know, so going forward we may not need to install the WebView Runtime at all - it'll always be up to date with Windows update.

I just took a look at my detection code though and I see that your error says the runtime is not installed which is clearly not true - it is but the problem likely is a version mismatch. I just ran through this code here on my machine to double check in debug and I don't see it failing, but I suspect there's some issue with the version detection that declares it as missing runtime when it really should say the runtime is out of date. 

I've added some logging to see why that is and that code is in 2.8.



There's also an `IgnoreWebViewVersionMismatch` which can be turned on to ignore the version check:

![image](https://user-images.githubusercontent.com/1374013/234116624-5747b0bb-cd67-49d4-9f94-7574ad7e116d.png)

However, you probably need to set that in `%appdata%\Markdown Monster\MarkdownMonster.json` to work if you can't start MM in the first place.

**Comment by Tony20221** [comment] 2023-04-24 23:07
@RickStrahl 
I installed the version from today and both versions say Webview is not installed. I already made the settings change in both.

"IgnoreWebViewVersionMismatch": true,

**Comment by RickStrahl** [comment] 2023-04-25 01:02
Hmmm... OK so I see your error in my logs.

![image](https://user-images.githubusercontent.com/1374013/234149187-6cebc204-9800-4225-8935-168defbbdf36.png)

That error refers back to this code:

```csharp
        public static bool IsWebViewVersionInstalledUi(bool showDownloadUi = false)
        {
            string versionNo = null;
            Version asmVersion = null;
            Version ver = null;

            try
            {

                //  *** THIS IS WHAT FAILS ***  meaning WebView is not accessible or lacking permissions perhaps
                // If version no lookup or parsing fails WebView is not available
                versionNo = CoreWebView2Environment.GetAvailableBrowserVersionString();

                // strip off 'canary' or 'stable' version
                versionNo = versionNo.ExtractString("", " ", allowMissingEndDelimiter: true)?.Trim();
                ver = new Version(versionNo);

                if (!mmApp.Configuration.System.IgnoreWebViewVersionMismatch)
                {
                    asmVersion = typeof(CoreWebView2Environment).Assembly.GetName().Version;
                    if (ver.Build >= asmVersion.Build)
                        return true;
                }
                else
                {
                    return true;
                }

                return true;
            }
            catch(Exception ex) 
            {
                mmApp.Log("WebView Version lookup failed.", ex.GetBaseException(), logLevel: LogLevels.Error);
            }

            if (!showDownloadUi)
                return false;

           // ... dialog  display here

           return true;  
}
```

**Comment by Tony20221** [comment] 2023-04-25 03:19
![image](https://user-images.githubusercontent.com/99626433/234166142-163858b9-bf09-4c20-ac01-e9b78764d0fc.png)

**Comment by RickStrahl** [comment] 2023-04-25 04:41
@Tony20221 - after a bit of experimenting I seem to have gotten stuck in the same WebView Runtime nightmare that you have been reporting now where I can't update or reinstall. 

Only a full uninstall seems to fix it.

What's really strange is I have several apps I created that use the WebView - the others are working, but MM refuses to launch. If I bypass the launch check (no in the dialog) MM launches, but the WebViews that drive the editor and preview don't work... Argh.

Checking to see if I can track this down.

**Comment by RickStrahl** [comment] 2023-04-25 05:29
Oh crap I think I found the issue which is totally unrelated to the actual WebView installation, but rather by the build.

I changed the build target to 'Any' from explicit `x64` and apparently this is causing the app to start in 32bit mode

IAC, could you please try downloading `v2.8.17` which has the properly targeted binary.

**Comment by RickStrahl** [comment] 2023-04-25 05:34
As a side note I'm looking into removing the forced installation from the installer. Since the WebView is now more or less becoming a system component that is updated with Windows I think I'll opt to start the app and then check if the WebView is installed. If not installed then re-direct to the installer to force install if not installed or out of date. 

Additionally I might not update quite as frequently to the latest versions of the WebView .NET components which should help let the automatic system updates keep the versions higher than the .NET components which is the other (besides no install at all) to force an update. If the .NET versions are a bit delayed (unless there's a problem that is specifically addressed by the component) then Windows update should take care of the update process.

The result of this will be that the MM installs will be much quicker and I can also potentially remove the installer binary and just link to the download instead. I'll be experimenting with this for a future update.

**Comment by Tony20221** [comment] 2023-04-25 05:44
After several tries, it finally worked. Thanks.

**Comment by RickStrahl** [comment] 2023-04-25 05:47
@Tony20221 and @HamedFathi Thank you both for your help...

**Closed** 2023-04-26 18:20 UTC
Labels: bug

**Comment by IainStevenson** [comment] 2024-04-09 05:39
FWIW: I am currently behind the versions on version 2.9.10 and had to rebuild my PC. 

I stumbled on the exact problem, with a twist.

I had WebView2 installed and could not UNInstall it vie the setup,exe - nothing happened. None of the above helped in any way.

I even cleared everything out, switched off my AV, cleaned registry manually and all files manually - nothing helped.

So in desperation I sought creative last stand solutions and after looking at the log, zeroed in on 

Unable to load DLL 'WebView2Loader.dll'

So confirming it wasnt in the installation folder, I found one elsewhere (there were about a dozen - I chose it from LinqPad7), copied it in to the installation folder - problem solved.

**Comment by RickStrahl** [comment] 2024-04-09 06:09
The WebView is now a Windows 11 component so you should in theory never have to install it any longer. You can check if it's installed in your `Programs` in Windows settings.

If for some reason you managed to uninstall it, you can manually install the WebView Runtime, but **you have to use an Admin install**. 

You can [download from Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH&ch=1#download) or by running the `MicrosoftEdgeWebview2Setup.exe` in the `BinSupport` folder of the MM installation. Make sure you **run either the downloaded version or the standalone as Admin** or it won't work.

But I suspect the issue is actually something else: Namely that the version referenced in the old SDK version of MM is now so out of sync with the runtime that it doesn't want to load it. You can turn off the version check in the configuration which should get you past that startup dialog.

**Comment by IainStevenson** [comment] 2024-04-09 06:54
I used all of trhe 'official' means of installing / uninstalling, both MM and WV2, both normal user and administrator modes  and tried the ignore version setting. Nothing worked at all! Very strange. I nearly gave up and walked away. I even regedit cleaned manually some of the residual keys left after uninstalling MM. Jsut in case tht made a difference, which it didn't.

The only thing that helped me (so I added it for community relief) was borrowing that one file from another app that uses webview2 loader and bingo.

Remeber this was a new Operating system build. It was a clean as it gets.

I was wondering if my AV interfered 'quietly' but cI ant get anything out of the logs. I use ESET - for reference.

the other thought struck me was that the OS has moved on and WebView2 has moved on version wise and the installer jsut decided not to deliver the loader DLL? But that is beyond my competence to figure out. If I had time and a VM capability I could work out the behaviour.

Anyway, I am jsut glad I got round it, and can carry on. I hope this little 'option' helps anyone else in the same place.

Thanks for the additional info though. Great product.
