### ISSUE TITLE
No interface :)

### ISSUE THREAD

**Issue by nZeus** [RickStrahl/MarkdownMonster#21] opened 2016-08-04 09:07 UTC
I've just installed the latest version of MM (0.42).
When I run the app, I see only border of the app, the rest is transparent:

![image](https://cloud.githubusercontent.com/assets/2727326/17396419/a9ba87d0-5a33-11e6-8d48-dbeb8a1a4300.png)

(this grey border is the border of MM)

**Comment by RickStrahl** [comment] 2016-08-04 15:27
Hmmm... that's odd. Does it show up as an icon on the task bar?

Can you check to see that you're running only a single instance of MarkdownMonster.exe in Task Manager? It's possible there might be a hung instance that's causing a problem. Kill all instances of MM and start again.

**Comment by nZeus** [comment] 2016-08-05 09:15
I've found the reason.
This happens when you connect to PC via TeamViewer. So that means that you cannot use MM on a remote PC.

If you want, you can close this issue. That's not critical for me

**Comment by RickStrahl** [comment] 2016-08-05 10:55
Wow, that's an odd one. I do know it MM works with RDP as I use it on several remote machines, so this must be something specific to TeamViewer and how they marshal the UI. I use TeamViewer myself quite a bit but haven't tried it with MM.

Closing but will check when I get access to another machine to try this out.

**Closed by RickStrahl** 2016-08-05 10:55 UTC

**Comment by punker76** [comment] 2016-08-05 12:16
@RickStrahl This issue is maybe caused by MahApps. I will invastigate this.

**Comment by RickStrahl** [comment] 2016-08-06 12:10
Thanks @punker76!
