### ISSUE TITLE
Bug: Program suddenly crashes

### ISSUE THREAD

**Issue by FlavioRyu** [RickStrahl/MarkdownMonster#977] opened 2022-09-21 16:30 UTC
Hi, I just started using the program today and everything was nice and well until the program closed itself suddenly, making me lose the file I was working on which was not saved. Not sure if this helps but here is the last 3 error logs:

```
21/09/2022 17:08:16 - AppDispatcher: CoreWebView2 members cannot be accessed after the WebView2 control is disposed.
The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)
-- CoreWebView2 members cannot be accessed after the WebView2 control is disposed.
Markdown Monster v2.6.9.0
10.0.19041.1.amd64fre.vb_release.191206-1406 - en-US - NET 4.8 - 64 bit
en-GB - en-US    
---
Microsoft.Web.WebView2.Core
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.set_Bounds(tagRECT Bounds)
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.set_Bounds(Rectangle value)
System.Runtime.InteropServices.COMException
---------------------------



21/09/2022 17:08:25 - License unregistered: 



21/09/2022 17:08:41 - License unregistered: 
```

PC specs:
* Processor = 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz   1.80 GHz
* Installed RAM = 64.0 GB (63.7 GB usable)
* System Type = 64-bit operating system, x64-based processor
* Windows Edition = Windows 10 Enterprise

Thank you.

**Comment by RickStrahl** [comment] 2022-09-21 16:47
@FlavioRyu Sorry to hear that...

It looks like the WebView control somehow got corrupted and shut down internally. This looks like a hard system crash in the browser that then triggered the shutdown.

Can you recall what you were doing at the time? Typing, switching windows, something else?

I see these errors occasionally in my crash logs, but they are very, very rare and I've not been able to track them down. The problem is they are system failures that originate outside of our codebase (from the browser) and then cause the browser to essentially shut down which in turn triggers the MM shutdown. I have issues open with the WebView team for better error handling in these scnenarios but unfortunately the shutdown events often don't fire. The shutdown interceptors allow you to save before the shutdown - but clearly that didn't happen here.

If you have any more information about the state of the application or what you were doing at the time of the crash that would be helpful.

+++ Rick ---

**Comment by FlavioRyu** [comment] 2022-09-22 10:30
Ah that's unfortunate...

I wasn't doing anything special and I cannot recall ***exactly*** what I was doing but I can give you a general description. I was watching a video saved in my local pc, and taking notes from while listening to it. So I was also switching between the video player and MM. I also had some tabs open in Edge which I was using, for example, to find a specific HTML color and I switched few times between MM and Edge to copy paste the color code and change color of some titles in the document.

One specific thing I recall is that when the shutdown happened I was typing very fast, as the video was going pretty quickly and I didn't want to pause it.

I also want to note that I think another shutdown happened before this bad one, where I was not using MM but browsing with Edge and I realised the program closed itself randomly. But as I had no document open there were no consequences about it.

I also had Chrome open the whole time, as I have multiple monitors.


Hope this helps.

**Comment by RickStrahl** [comment] 2022-09-25 16:42
MM uses the Edge WebView, but it's using its own private environment so any other Edge instances should have no effect on it. 

I just discovered a possibly related bug that concerns where the temporary environment is stored.

Are you using the default configuration folder or have you customized your configuration storage folder to another location (like DropBox or OneDrive)? If so, there was a bug where the WebView environment ended up in the shared folder which could cause corruption if multiple machines were using MM.

**Comment by FlavioRyu** [comment] 2022-09-26 10:12
No, I had just installed it and didn't change anything in the settings. I might have messed with some themes, but that's about it. I was just using it with the default settings in my local pc.

Now that I think about it, I have installed it on the corporate pc, which was connected to the corporate network. Not sure if this has anything to do with Edge WebView.

**Comment by RickStrahl** [comment] 2022-09-30 03:03
So is this a repeating problem or a one off?

I use MM all day long I have not seen a hard crash in months. Not saying it's not happening but saying that this is unusual. We do see a fair amount of issues with the WebView dying in our error logs, but relative to the overall load of uses it's a fraction of a fraction of a percent of usage.   The most common scenario is when the Edge temp data gets corrupted due to multiple different machines accessing the same Edge profile.

**Comment by RickStrahl** [comment] 2022-10-05 19:07
Closing since no further response and not enough info to do anything about at this time. If it occurs again and there's more information feel free to reopen this issue or create a new one.

**Closed by RickStrahl** 2022-10-05 19:07 UTC
