### ISSUE TITLE
Portable version should not use %APPDATA%

### ISSUE THREAD

**Issue by mikeyww** [RickStrahl/MarkdownMonster#300] opened 2018-01-11 10:43 UTC
The portable version should not use the Windows %APPDATA% directory, because the program is then no longer so portable. Portable versions should store all settings in the portable directory.

Version = 1.8.12

**Comment by RickStrahl** [comment] 2018-01-11 11:52
Well I don't agree, but you can configure Markdown Monster to do what you want to do.

* Create a Settings folder (or whatever) in your install folder
* Run Markdown MOnster
* Open Settings
* Edit the CommonFolder to `CommonFolder": ".\\Settings"
* Exit Markdown Monster and restart

**Comment by mikeyww** [comment] 2018-01-11 12:24
[MarkdownMonster.zip](https://github.com/RickStrahl/MarkdownMonster/files/1622481/MarkdownMonster.zip)
I tried that. I have the following.
  "CommonFolder": ".\Settings"
Nonetheless, the program still creates and uses the %APPDATA% subdirectory!
I have attached my portable settings file from e:\data\utils\markdownMonster\Settings\MarkdownMonster.json.

**Comment by RickStrahl** [comment] 2018-01-11 21:26
Did you follow the steps I outlined though? It will not work if you just change the value in the JSON file on its own because the support file has to be created before you restart. Only updating the settings from within MM will force the settings to be saved and the support file that points at the right location to actually get written.

I just tried this here and it works for me (with a %AppLocalData%\Settings folder).

**Comment by RickStrahl** [comment] 2018-01-11 21:32
FWIW - it's on the todo list to make some configuration tasks easier with this one at the top of the list. Basically there will be a special operation for changing the startup folder that will automatically save and create the required file and prompt for a restart.

**Comment by mikeyww** [comment] 2018-01-11 22:33
Great!  Re your earlier question: I followed the steps, but I have one difference in how I am using the portable version. I am using a portable folder on a different drive, not one under %APPDATA%. With this scenario, I even tried the absolute full path to that directory, including double-\, but the program still created and used its own %APPDATA% subdirectory. You might try this using a different partition, a USB drive, or something like this to reproduce the problem.

**Comment by RickStrahl** [comment] 2018-01-11 23:40
I'll take a look but on first thought this shouldn't make a difference because the location is based on the startup folder of the application. MM immediately on startup resets the startup folder to the EXE's location (just in case some odd command line pathing was used) so it should always be able to find files in that location.

However - you may have a permissions problem. You have to be able to write to that location in order for the config file to be created. Also make sure there's not some other instance running that was started from somewhere else.

The problem with a relative path like `.\\Settings` is if you run multiple instances (dev and a full install  me for example, but perhaps full install and portable install and a chocolatey install) each is going to use their own private settings which can be very confusing which is why we force the shared folder by default.

**Comment by mikeyww** [comment] 2018-01-11 23:58
It almost works but not quite.  There is a way to get it to work, and I finally got it to work. I had to change the common folder setting in both %APPDATA% and then my portable folder, and between making these two changes, re-run MM a bunch of times because of this "pointer loop" issue where each of the two settings file was pointing to the other directory! There should be a much more usable way of implementing this change for the user!

**Comment by RickStrahl** [comment] 2018-01-13 11:15
I agree this is too difficult at the moment and will get addressed eventually.

For now, we have to follow the steps I outlined exactly for this to work.

Closing since more visual configuration is already on the work list.

**Comment by mikeyww** [comment] 2018-01-13 12:00
The steps don't work when using a portable folder outside %APPDATA%. Many other programs handle this situation in a straightforward manner-- enabling portable use without using %APPDATA%-- simply by creating a way (e.g., a file serving as a flag) to notify the program that it is running in portable mode, and then looking for the settings subdirectory in the program's directory instead of in %APPDATA%.

**Comment by smaragdus** [comment] 2018-06-14 00:18
I agree with [mikeyww](https://github.com/mikeyww) that the so-called "portable" version is not portable at all. I would like to suggest a couple of possible solutions which would make [Markdown Monster](https://markdownmonster.west-wind.com/) **really portable**:

- command-line argument - if Markdown Monster is started with a special parameter, for example `MarkdownMonster.exe -portable`, it saves all settings in program folder, not in AppData;
- portable flag - on program start Markdown Monster checks program folder for `portable` flag and if such flag is to be found Markdown Monster saves all settings in program folder, not in AppData;

Either option would be fine for me. Another possible option might be that a special sub-folder in program folder (for example `Data` or `Settings`) triggers portable mode forcing Markdown Monster to save settings in program folder, not in AppData.

**Comment by RickStrahl** [comment] 2018-06-14 08:32
The problem with that is if the app installs into a protected folder (like Program Files!) you can't write in the start folder. This is why we use that folder.

There's already logic in MM that can redirect the common folder:

https://markdownmonster.west-wind.com/docs/_4x20odmu3.htm#how-it-works

But as it stands right now it still needs at least that one file in the %appData% folder so the data can be redirected. I suppose we could change that so that it first looks for the same file in startup folder and then looks in %appdata%.

**Comment by mikeyww** [comment] 2018-06-14 09:36
A simple command-line argument like "-portable" could fix everything simply. You could then also simply notify the user if the portable directory has no write access.

**Comment by smaragdus** [comment] 2018-06-14 16:18
@RickStrahl 
I think that users who would use a special start parameter would be in most cases educated enough not to put Markdown Monster in write-protected location. I also presume that 90% of the users would choose the installer. Of course if you implement a command-line argument which forces portable mode and thus writing to AppData is avoided you may update the documentation for [Portable Version ](https://markdownmonster.west-wind.com/docs/_4t90rhfy9.htm). For me fully portable version is a must- I backup all my portable programs (with all their data and settings) to an external drive.

**Comment by mikeyww** [comment] 2018-06-17 13:34
Sounds promising!

**Comment by smaragdus** [comment] 2018-06-17 19:14
@RickStrahl 

I have just checked version **1.11.16** and I can confirm that it is portable, I didn't find any traces in AppData. But the portable version still writes to Windows registry:

`HKEY_CLASSES_ROOT\Markdown Monster`

I prefer that portable versions do not touch Windows registry at all. Is this avoidable in future releases?

**Comment by smaragdus** [comment] 2018-06-17 19:15
May I ask off-topic questions here or I would better open new issues?

**Comment by RickStrahl** [comment] 2018-06-17 23:35
Yeah we need a unique key for registration and it has to be separate from the registerkey that's stored in the common folder. It'll work without that, but if you register it has to be there. The alternative is we do web based key generation which IMHO would be worse.

**Comment by mikeyww** [comment] 2018-06-18 10:37
Thanks for the revision.

**Closed** 2018-06-26 17:40 UTC
