### ISSUE TITLE
Mark Down Monster not able to open files

### ISSUE THREAD

**Issue by GregFuhrmanTT** [RickStrahl/MarkdownMonster#900] opened 2022-01-03 15:53 UTC
This is the error that I get when trying to open a folder to open a file.

![image](https://user-images.githubusercontent.com/88348746/147951395-c2992cd5-cf8d-44e4-9024-369f57321720.png)

Running 2.2.2.1

**Comment by RickStrahl** [comment] 2022-01-03 19:26
Sorry, I'm not sure what you mean by _open a folder to open a file_? There are a lot of ways to open files, so could you be more specific? Via Open dialog? From the Folder Browser? From Explorer? From the Command Line?

Can you give me reproducible steps?

**Comment by GregFuhrmanTT** [comment] 2022-01-03 19:41
Absolutely, it happens at all the dialogs when opening a file. 

- Open Document (ctl-o) in the quick menu (main splash page). 

![image](https://user-images.githubusercontent.com/88348746/147971915-19ca5cca-4292-4ffe-8f72-e2127dc56881.png)
  

- Clicking on the folder icon in the upper left corner. 

![image](https://user-images.githubusercontent.com/88348746/147971827-7883eb39-01ec-43b2-a386-86cb20a8fbb4.png)

- File Open 

Double clicking on the file will give an error.
![image](https://user-images.githubusercontent.com/88348746/147972244-3e0e0105-db90-43e9-938d-e0a9f7cae72b.png)

Once this method is used. Clicking on the folder icon in the upper left corner will search for the file and not give this error.

https://user-images.githubusercontent.com/88348746/147951395-c2992cd5-cf8d-44e4-9024-369f57321720.png

Some files will open while others will show the error that it cannot be located.

**Comment by RickStrahl** [comment] 2022-01-03 19:46
Hmmm.... I suspect this is caused by the long path - the path probably exceeds the 256 character basic Windows path limitations. 

Just for kicks to verify can you copy the folder somewhere lower in the hierarchy and try same steps? 

If so there's no easy solution as the standard file open APIs don't work with long file names unless special file APIs or custom file syntax is used.

**Comment by GregFuhrmanTT** [comment] 2022-01-03 20:03
Yep, it will open when it is moved lower in the hierarchy! 

I will have to restructure my repository location. 

Thanks, that explains why some would open and some would not.

**Comment by RickStrahl** [comment] 2022-01-03 20:23
Yeah I just checked and verified that long filenames fail by creating a very deep file hierarchy. Fails pretty much any way you try to open the file. Curious, which way worked for you to get it open since MM does no mitigation for long file names?

Also checked with VS Code and although it managed to open the file it was also acting weird. I was able to save the file once but after that the file was in some weird state where I couldn't edit it anymore. VS Code appears to use the `\\c:\...` path prefix syntax to get the file opened.

While this failure in MM really is not great, we also have to recognize that 255 character filenames are very, very long path hierarchies. I found that out trying to create the hierarchy just now for this file :smile:

I could see fixing this for opening and saving, but the problem is that there are literally dozens of other file save scenarios for other assets and resources that would also have to be adjusted. I've been through this with another Console utility some time ago, and even when it works using long filename syntax or custom long file APIs the behavior is flaky as hell. So I'm not sure if this is a worthwhile change to make.

It sure would be nice if .NET provided a native way to deal with this given that it wraps the Windows API and its limitations, but alas... here we are.

While I could probably fix this for file opening and saving pretty easily via

**Comment by GregFuhrmanTT** [comment] 2022-01-03 20:43
Thank you for everything. 

I was dragging the file into Chrome and copy / paste the content in a new file. This knowledge will help so much.

**Comment by RickStrahl** [comment] 2022-01-03 22:49
So here's a possible solution to make long filenames work:

**Comment by RickStrahl** [comment] 2022-01-03 23:09
Well the good news is that MM can load and save files with these settings in place. But unfortunately the Chromium preview has problems resolving related resources using these paths. Apparently the main file can render fine, but related assets like an image do not work:

![image](https://user-images.githubusercontent.com/1374013/147990014-05a158a0-0766-4665-bc24-d1eea308c829.png)

So while this is nice in that MM can at least load and perform its file functions, this is a pretty serious limitation.

So same advice as before: It's better to avoid 255+ paths if at all possible just to avoid problems with some applications.

**Closed** 2022-01-05 01:37 UTC
