### ISSUE TITLE
No warning in response to modifying a read-only file

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#586] opened 2019-10-11 17:28 UTC
Edit a file. Put content into it. Save it. Exit out of MM.

Outside of MM, change that file's properties to be read-only.

Open that file in MM. Make a change. The filename in the tab now shows an asterisk next to it to indicate that a change was made.

Now, Ctrl+S or File | Save to save the change. Nothing is saved, nothing indicates that the save didn't succeed (that is, there's no warning message displayed in a popup window or anywhere else), and the asterisk doesn't go away.

Now close the file or exit MM. Now MM indicates with a popup that the file has been modified, and asks, "Do you want to save changes?" Respond yes, and the file closes, but the file still has not changed. You can confirm this by opening the file back up again to notice that your changes didn't take.

There really should be some warning that a file is read-only and that changes will not be saved -- preferably right when a user attempts to make a change, but certainly when the user tries to save those changes.

**Comment by RickStrahl** [comment] 2019-10-11 19:49
Oh wow - wonder how this fell through the cracks this long.

Took a quick look and it looks like a regression bug when I updated the code a while back for the auto-save logic. There's a missing return statement in the error handling block. Will test some more and post and update.

Thanks.

**Comment by RickStrahl** [comment] 2019-10-12 22:58
Fixed in 1.19.9.3

**Closed by RickStrahl** 2019-10-12 22:58 UTC
Labels: bug
