### ISSUE TITLE
V2.6.5 - Pipe Table formating increase column sizes

### ISSUE THREAD

**Issue by rowtoripo** [RickStrahl/MarkdownMonster#969] opened 2022-07-14 09:51 UTC
On pipe tables using the "format table" function increases the size of the column on every run. 

Example :
```
| A | B |
|---|---|
| 1 | 2 |
```

Click right and click "format table" results in:
```
| A  | B  |
|----|----|
|  1 |  2 |
```

**Comment by RickStrahl** [comment] 2022-07-15 22:37
Thank you. 

Recent changes broke this in a regression. Code wasn't trimming off the leading space - recent changes in Grid tables needed to preserve leading white space, but this doesn't work for pipe tables in the same way, so now formatting and parsing will strip all leading white space since it has no meaning in Pipe tables. 

Fixed in 2.6.5.1

**Closed** 2022-07-19 16:52 UTC
Labels: bug
