### ISSUE TITLE
Monster shifts to another monitor upon minimizing on Windows 10

### ISSUE THREAD

**Issue by ajit555** [RickStrahl/MarkdownMonster#376] opened 2018-05-20 04:40 UTC
OS Name: Microsoft Windows 10 Pro
OS Version : 10.0.17134 Build 17134
Markdown Monster version: 1.11

Issue:

I use two monitors. One is configured as "Main Display" in display settings. I intend to use the Monster in other monitor. 

1. When I open Monster, it opens in main display.
2. I drag it to other display.
3. I minimize it in other display.
4. When I reopen the Monster, it opens in the main display.
5. I again need to drag it to other display.
6. And the cycle continues.

**Comment by RickStrahl** [comment] 2018-05-21 19:27
Not sure I understand.

When you say 'reopen' do you mean un-minimize from the task tray?

All that works for me with multiple screens. There is an issue if a window is minimized and you close MM then it will not remember the screen because minimized screen settings are not saved. In that case it'll open whatever the last saved location was.

**Comment by ajit555** [comment] 2018-05-22 09:29
When I said 'reopen', I meant "un-minimize" from the taskbar. While working on documentation, I need to minimize Monster many times, and everytime, it opens in another monitor when I "un-minimize", then I need to drag the app into my working monitor.

Please see the attached video.

[VID_20180522_145446.zip](https://github.com/RickStrahl/MarkdownMonster/files/2025915/VID_20180522_145446.zip)

**Comment by RickStrahl** [comment] 2018-05-22 10:35
Thanks...

I see what you're doing but I can't duplicate it. I have basically the same setup as you do, and when I drag a window to the second monitor (right), maximize and then minimize, then un-minimize the form comes back on the same monitor it was on. If I don't maximize or full window dock I also don't see any issue and the form comes back on the correct screen. When maximized occasionally though the size is off as it restores not to maximized but to the actual size. But it's usually somewhat different but not completely wrong.

FWIW, try without maximizing the window and see if you get different behavior. There's special handling for minimized and maximized windows  when size is remembered and that can cause some funky behavior. It's possible that a maximized window will be larger than they actual monitor dimensions and that'll cause MM to resize to the default.

**Comment by ajit555** [comment] 2018-05-23 01:02
Monster current version: 1.11.4

Interestingly, your suggestion - "FWIW, try without maximizing the window and see if you get different behavior." seem to solve the problem completely :)

What I did:

1. Let the video I sent be the starting point. The left side tall monitor and right side main monitor.
2. When I opened Monster, it opened in tall monitor in full screen mode.
3. Earlier I used to drag it to right side monitor in maximized mode and was getting the issue. 
4. This time, first I "restored-down" in left tall monitor, and then dragged to right monitor and maximized there.
5. Now when i minimize and restore the monster in right side monitor, it remains there only. 
6. But now its working okay even when I drag from left to right monitor in maximized mode, minimize it and restore, it opens in the same right side monitor. (the main issue that I reported).

Somehow, that "ONE-TIME" activity of first restoring-down (without maximizing) and dragging to other monitor and then maximizing solved the complete issue :)

Thanks a lot for your suggestion. Seems like I hit some edge case.

**Comment by RickStrahl** [comment] 2018-05-23 05:46
I just can't duplication the behavior you're seeing to occur under any circumstances but I don't have a vertical screen. I suspect the issue is the detection logic of what is considered off-screen and MM thinks the location on the second screen is off-screen and then restores to the default location.

**Comment by ajit555** [comment] 2018-05-24 03:46
Monster current version: 1.11.4

Thanks for the reply. Below is the pattern on my machine:

1. In two monitors, one of the monitor is designated as "main display" in windows display setup.
2. When I open MM, it opens in the main display and its icon is shown in the main display taskbar.
3. When I drag MM to another monitor, the icon also shifts to another monitor's taskbar.
4. When  I minimize MM, the icon shifts to main display and it restoring it opens in main display. [This happens only one time].
5. After this, when I drag the display again from main to other monitor, the icon remains on the taskbar of other display and it restores properly in other monitor only.

Well, I have sort of getting used to this pattern and it is less bothering me now :)

**Comment by RickStrahl** [comment] 2018-05-25 19:09
Uhm... not sure what you mean by the 'icon is shifting to the other screen'. 

When you open an application in Windows, the icon in the task bar shows on all monitors.

**Comment by ajit555** [comment] 2018-05-26 04:36
_"When you open an application in Windows, the icon in the task bar shows on all monitors."_

Not necessarily, it is configurable in "taskbar settings".

Normally, using multiple monitors, on the taskbar, I like to see only those application buttons which are open in that monitor. 

So, if MM is open in left monitor, its icon/button shows on the left monitor and vice versa.

Normally I have a dozens of apps open at any time and it helps me to reduce the application buttons clutter on the taskbar. 

It can be configured as below:

![image](https://user-images.githubusercontent.com/194380/40572489-72e61cec-60cb-11e8-800b-b8453d87f179.png)
![image](https://user-images.githubusercontent.com/194380/40572492-8342563c-60cb-11e8-92c3-bb69c2cca6d2.png)

**Comment by RickStrahl** [comment] 2018-05-31 03:53
Ok so I set that up the same way as you have but it still doesn't behave the way it does for you. For me the window minimizes on the same screen and comes back on that same screen. I also played around with second monitor placement to left and right and I don't see this behavior in either way.

**Comment by ajit555** [comment] 2018-05-31 14:10
In my above reply, point#4, "When I minimize MM, the icon shifts to main display and it restoring it opens in main display. [**This happens only one time**]."

It just happens one time, and after that, it works normally. Its okay as of now for me.

**Comment by RickStrahl** [comment] 2018-06-01 23:37
Not saying it's not happening to you - I saw the video. Just saying I can't duplicate it with those exact same steps and what looks like the same configuration. Not sure what to do about it since I don't see it and haven't heard of a similar report from anybody else.

One more thing - what is your monitor layout in Display Settings?

**Comment by ajit555** [comment] 2018-06-03 02:28
I have attached two monitors to my Dell laptop. 
![monitors](https://user-images.githubusercontent.com/194380/40882560-a68722d8-6703-11e8-8f79-3124db1e7da2.jpg)

The laptops screen (1 in the image below) is disconnected

My main monitor is a 4k monitor (2) in landscape mode, primarily used as a code editor.
![main-monitor](https://user-images.githubusercontent.com/194380/40882525-860868d8-6702-11e8-90de-567b06c6367a.png)

My secondary monitor is FHD monitor (3) in vertical / potraint (Flipped) mode, mainly used for reading documents and application preview.
![secondary-monitor](https://user-images.githubusercontent.com/194380/40882526-8b3bdcd6-6702-11e8-9175-cce1eb17b86b.png)

**Comment by RickStrahl** [comment] 2018-06-04 20:48
Nice setup :-)

UNfortunately that still doesn't help in providing a repro case. I have the same setup between your two right most monitors which seems what you were using for the video and in that case I see the app minimizing and coming back in the right screen each time.

I don't know what else to check. I'm going to close this. Feel free to re-open if you can think of some other information that might help.

**Comment by ajit555** [comment] 2018-06-06 01:56
Sure. If the behavior changes in subsequent updates of Windows / MM, I would update this issue. Thanks.

**Closed** 2018-06-08 05:01 UTC
