### ISSUE TITLE
Error: "Specified cast is not valid" when right click

### ISSUE THREAD

**Issue by robc-io** [RickStrahl/MarkdownMonster#517] opened 2019-05-03 22:39 UTC
I just started getting this error after I updated to the most recent version yesterday when I right click anywhere within the editor frame of the app.  

"Message from webpage" -> "Specified cast is not valid" 

I have to close the window and then it goes away and eventually comes back (this is the second time). 

Not a big deal really but it is an error.

**Comment by RickStrahl** [comment] 2019-05-03 23:02
I can't duplicate that behavior. Anything else going on that might be more specific?

Right click should bring up the context menu.

Can you download the latest version. There were changes to the context menu and some interim releases may have had a problem. Grab latest from the download page.

**Comment by robcxyz** [comment] 2019-05-05 03:33
Yeah it only started when I did download the new one about 4 days ago or so.  I'll try to pay attention to the events that lead up to the error and let you know. 

Let me know if there is any newer version than what I have otherwise I'll let you know if I find a pattern.

**Comment by RickStrahl** [comment] 2019-05-05 04:42
I think the latest is newer. 1.16.16 is up now. pretty sure the issue you're having is due to one of the interim builds.

**Comment by NoahAndrews** [comment] 2019-05-16 03:04
I just experienced this on 1.17. Unfortunately, the only thing in the error log was from October. Earlier this was working fine, so I'm not sure what caused it. Restarting the application fixed the issue.

**Comment by NoahAndrews** [comment] 2019-08-23 15:22
Experienced again on 1.18.12. Again, there's nothing in the log, and restarting fixes it.

**Comment by RickStrahl** [comment] 2019-08-23 16:45
How is this error showing up? Are you getting the error dialog? If you do the message should show up in your error log. If not - make sure the log file has permissions (if you're using a portable install in a location that's not a user folder).

**Comment by NoahAndrews** [comment] 2019-08-23 16:50
It's a little popup. I wish I had taken a screenshot, sorry. I'm not using the portable version, and my most recent log entry is from May 16, literally the day after the last time I reported this bug, so it seems extra unlikely that there's a permissions issue with the log file. For good measure, I verified that my user account has full access to the file.

**Comment by RickStrahl** [comment] 2019-08-23 21:44
If it's the message box with a red x icon on it, that's the standard error page after an unhandled exception which is what I would expect in the case of a hard error on a popup. However, when that dialog pops up, the error is logged both locally on disk and to the error reporting service.

A few versions back (I think when this was originally reported) there were a number of these errors popping up in the logs, but that particular issue was fixed and I haven't seen any more of these errors recently with newer versions. Are you sure you're not running an old version by chance? Perhaps from a dev build or?

If you know when the error happened I can check my logs, but it would have to be somewhat close (time of day + timezone  - locale would also help especially if not en-US).

**Comment by NoahAndrews** [comment] 2019-08-24 01:53
I'm in the Eastern US time zone. I'm on my phone, so I can't see the exact time I posted, but I wrote the most recent report comment within a couple of minutes from when I saw the error. 

I definitely wasn't running a dev build, as I didn't know where to download dev builds until later today (again, you can look at the GitHub comment timestamps).

**Comment by RickStrahl** [comment] 2019-08-24 19:06
Yeah I don't see anything in the online logs either that matches this failure. If it's not logging locally it's unlikely to send a report to the online log service.

**Comment by RickStrahl** [comment] 2019-08-24 19:11
Come to think about it, there was a brief release that was put out that had set a registry flag incorrectly. Maybe try the latest release from the site which will clean that up. 

That error would cause an IE error *if IE script debugging is explicitly enabled* in the Internet Explorer settings. It was very briefly released - I updated the package quickly after but it was out there for a few hours. IAC any of the current releases will address this particular issue.

**Comment by NoahAndrews** [comment] 2019-08-24 19:33
Hmm. Did the brief release have a different version number, or was it also released as 1.18.12?

FWIW, I updated via Chocolatey. 

Unfortunately, I can't reproduce this issue after restarting the program, so it's hard to say if updating to a particular version fixes it or not.

**Comment by RickStrahl** [comment] 2019-08-25 00:07
It was really short lived and I updated as soon as I realized the problem. same version # but possible that it was downloaded by a few people. The issue was caused by a registry setting that didn't set the IE compatibilty correctly - it gets overwritten when re-installing.

Keep an eye on it and do let me know if it occurs again along with a screen shot if you can get it - that'll be helpful.

**Comment by NoahAndrews** [comment] 2019-08-25 20:19
Will do

**Comment by jovibor** [comment] 2019-10-06 03:46
![image](https://user-images.githubusercontent.com/5625787/66263945-93b5d480-e847-11e9-9e74-8895cdff1abc.png)
Can confirm.
It appears suddenly and only app's restart helps.
Working with the 1.19.8 ver, but it happened earlier as well. Can't easily get the steps to reproduce, but it's definitely here. Context menu doesn't popup at all.

**Comment by RickStrahl** [comment] 2019-10-06 21:41
I have seen this as well and it seems to occur if MM is sitting for a long time idle and then is re-activated (possibly after sleep mode). It's rare even then.

The error is caused by the generic page error handler.

To fix I don't think you need to restart MM but closing or reloading the document should do it. You can close and re-open the tab, or press F5 to reload it. That should restart the scripts on the page that might be causing the issue.

**Comment by RickStrahl** [comment] 2019-10-06 21:42
So added some alternate handling of this error here:  8464cf8a2881975fbfb486c0da95bd15117d6dfd

First - the dialog has been removed and now there will be a more useful status bar message instead. The error is now also getting logged so hopefully this will provide more information to us to figure out what actually is causing the problem.

**Comment by RickStrahl** [comment] 2019-10-15 05:47
Closing for now. If this keeps popping up and a problem, please reopen.

**Closed by RickStrahl** 2019-10-15 05:47 UTC
Labels: cant duplicate
