### ISSUE TITLE
@ icons disappear in the PDF

### ISSUE THREAD

**Issue by Ben-CO7** [RickStrahl/MarkdownMonster#1136] opened 2024-10-11 14:57 UTC
When using Save to PDF, the icons (that show in the preview) disappear in the PDF.

Markdown
![image](https://github.com/user-attachments/assets/ebd434c3-3a82-4795-b0ae-ed9d8b5af48a)

Preview
![image](https://github.com/user-attachments/assets/2f20c4df-a7a6-4b6c-b826-105c696cc2fd)

PDF
![image](https://github.com/user-attachments/assets/54435264-ce7f-40c1-be29-dc51c964c1ac)

This wasnt happening until I got the license and it upgraded MM to the latest version.

**Comment by cfurubotten** [comment] 2024-10-18 00:58
Hello Markdown Monster Developers,
Ben-CO7 and I work together. We have 3 paid licenses.
As he wrote above that when he recently updated his paid copy of Markdown Monster, the icons no longer appear when he uses **Save to PDF**. When he installed, the newest version the installation also required a runtime update.

Our colleague in Asia has the previous version and hers works. My paid copy worked before I upgraded. Should we uninstall the new version and install the last one to see if this fixes the issue?

Has anyone here experienced this issue or know about it? Thanks!

**Comment by RickStrahl** [comment] 2024-10-18 01:16
I think the only reason that worked before is because we didn't use a default style template (Print to PDF). That template hardcodes the font used. 

The problem is that there's no way to embed fonts. The reason it would have worked is that you actually have the FontAwesome fonts installed locally - if it goes to another machine that doesn't have the fonts installed the fonts are likely not going to work.

You can customize the template and add FontAwesome into the font selection (or use one of the non-print templates) to get the old behavior but I wouldn't recommend it as it won't work consistently.

You can get this to work by using Print To PDF which works differently (graphically rendering the content), but there are other limitations to the print output.

**Comment by RickStrahl** [comment] 2024-10-19 05:43
Just to be sure I went back and looked at my last v2 release and this works no differently there.

There have been changes in v3 switching from FontAwesome 4 to 6, but it doesn't work in either case with the PDF generator. I tried a few things to see if I would be able to explicitly embed icons, but that simply doesn't work with wkhtmltopdf. 

Only way is to Print to Pdf.

**Comment by RickStrahl** [comment] 2024-10-19 22:29
I'm adding WebView PDF output support to Markdown Monster and going forward you'll be able to switch between wkhtmltopdf and WebView print modes. Both have some advantages and disadvantages.

**WebView Advantages**  

* **Closer to HTML Output**  
The WebView produces much closer PDF output to the original HTML in the previewer. This is due to the newer Chromium engine used in the WebView including support for media content, and it's dymnamic rendering of content so script rendered output is captured (like code colored code snippets for example).

* **Significantly faster rendering**  
WebView rendering is considerably faster than wkhtmltopdf for large documents. This is due to the much newer and more performant Chromium engine - same used in the previewer or the latest Chromium version installed with the WebView.

* **Print Preview matches output closely**  
The print previewer and output generated by the WebView PDF generation use the same engine, hence you can expect the same output.

**WebView Disadvantages** 

* **No header or Footer Support**  
I have not been able to make the WebVIew engine (or the rendered printed HTML document) to render headers or footers. Still looking into this but at the moment this does not look possible.

* **Page Size limitations (will be fixed later)**  
Currently page sizes can't be adjusted for PDF documents so it uses default page sizing for your browser and locale.

Functionality is available in the latest preview release (.NET 9.0 release) - it's a bit rough at the moment as non-supported options still show in  the PDF dialog.

**Comment by RickStrahl** [comment] 2024-10-22 21:54
![image](https://github.com/user-attachments/assets/b75f4a4f-14f8-4607-b6a8-13004174d044)

**Comment by Ben-CO7** [comment] 2024-10-24 16:14
I try using Print to Pdf, but the PDF ends up with strange font irregularities where some letters seem randomly bolded.

The old version of MM  where the icons did show up in the PDF was 3.0.0.31. Is there a way I can revert my license back to that version?

**Comment by RJS32** [comment] 2024-10-24 19:39
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Siphompeks** [comment] 2024-10-25 00:48
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by RickStrahl** [comment] 2024-11-06 03:04
Try this again with v3.5 and open a new issue if this still doesn't work. It should work with the new PDF print engine.

**Closed by RickStrahl** 2024-11-06 03:04 UTC
