### ISSUE TITLE
Feature: Remember Windows Position

### ISSUE THREAD

**Issue by SyntaxDreamer** [RickStrahl/MarkdownMonster#1158] opened 2024-12-11 10:55 UTC
I have 5 displays, with a DisplayLink Dock.

When I open the MarkdownMonster, it always opens it by default on the monitor that is set as the main (default) one on Windows 11.

It would be nice if it would remember the windows position and monitor like other applications. For example, if I moved it to monitor 3 and close it, it should then always open on monitor 3.

The same should be true for the window used by the external preview option.

Most Windows applications do this by default for years. They remember where it was last opened, that means monitor, and even position, if in case it was resized.

**Comment by RickStrahl** [comment] 2024-12-11 21:17
I've added a fix for the Maximized window positioning. Maximized windows should now remember their position and come back on the monitor they were last run on (assuming the screen layouts stay the same).

v3.5.6.2

**Comment by RickStrahl** [comment] 2024-12-12 18:21
Incidentally this patch also fixes a related issue where the window in some cases double positions and appears to bounce around - specifically in Maximized modes but also when relocating to other screens. 

This update should snap windows into the right place exactly once (as it should be) in all situations.

**Comment by SyntaxDreamer** [comment] 2024-12-14 15:10
Seems related to presentation mode. See #1155

**Comment by RickStrahl** [comment] 2024-12-16 01:15
> Reporsted from #1155 to keep the thread focused

Sorry, was busy. Downloaded latest version 3.5.6.2.

Good news. The copy error is gone. Fixed.

The bad news. The windows/monitor position is now worse than before.

**Before:**
It was always launching the application on my main monitor.

**After:**
Now it's launching it split between 2 monitors, offset, only a little part of the bottom is visible, the other parts are offset from the view port. I just move them and maximize, hitting windows shortcut keys, but for someone who does not know the shortcuts on Windows they will be stuck without being able to select the application and drag it back with their cursor. This can be very frustrating for some people if an application goes offset, and it's not visible.

_The way I open it:_

I just open a markdown file, I set .md files to use Markdown Monster as default. In the settings I have the checkbox option enabled 'Open in Presentation Mode' because I mostly want to open files to read them first, as documentation by default. 

I decided to test this with the setting off. And then it seems to work. It seems to remember the monitor, and it opens the applications correctly. I then check the setting again, and it goes off-screen once more, between 2 monitors (none of which are the one I actually set before).

It seems to be isolated to when Presentation Mode is turned on.

The JSON after closing the app (with **Presentation Mode** checked)

```json
  "WindowPosition": {
    "Top": 1080,
    "Left": 516,
    "Width": 1050,
    "Height": 690,
    "InternalPreviewWidth": 883,
```

I think you just need to look into Presentation Mode, I will turn it off for now, not a big deal, but at least we know where the bug is 😊

**Comment by RickStrahl** [comment] 2024-12-16 01:19
Confirmed. I see different behavior than you, but it's definitely not right.  

On my machine with **Open in Presentation Mode** checked, if I close the monitor on my second monitor, it'll reopen in what seems like a random position on my main monitor which is very odd. 

I'll have to take a look and see.

Presentation mode on startup is tricky due to timing of the document loading and I think the hacks around waiting for the document to be available are causing this weird behavior.

Taking a look...

**Comment by RickStrahl** [comment] 2024-12-16 03:35
Give 3.6.7.2+ a try - it should have the presentation mode issue fixed.

As suspected this was a timing issue with the notification bit getting fired before the window had properly initialized which threw off the resizing.

**Closed** 2024-12-27 19:48 UTC
Labels: bug
