### ISSUE TITLE
Icons do not work when enclosed in **...**, ie bolded

### ISSUE THREAD

**Issue by djgm501** [RickStrahl/MarkdownMonster#1142] opened 2024-10-30 18:16 UTC
In your samplemarkdown.md file you have:

\* To create a \*\*New Document\*\* press \*\*Ctrl-N\*\* or \*\*click @icon-plus-circle\*\* on the toolbar

The output in the preview screen:
* To create a New Document press **Ctrl-N** or **click on the toolbar

Removing the bolding produces the desired result:
click {plus-circle icon} on the toolbar

I just installed MM 3.4.5 with .NET 8.0.10

TIA
David

**Comment by RickStrahl** [comment] 2024-11-06 03:03
Yeah that's to be expected as the icons are not regular fonts  and don't have bold/italic etc. versions. They should render in the context of bold/italic etc. except in some situations where they are at the end of a line of text which is a quirk in Markdown due to the HTML tag expansion that occurs for these icons (ie. `**Some text <i class="fas fa-home></i>**`). There needs to be more text or at least some space between the HTML tag and the Markdown 'tag'. 

The Sample doc has some invalid markup actually related to this - I keep forgetting to fix this.

**Comment by RickStrahl** [comment] 2024-11-07 02:37
The fix for this is pretty simple. Since it's caused by the icon being at the end of the bold block you need to terminate the bold block before the icon.

As mentioned above the problem is the icon expands to raw HTML and raw HTML needs to be either on its own line or have some additional content behind it otherwise it will fail.

This works:

~~~
* To create a **New Document** press **Ctrl-N** or **click** @icon-plus-circle  on the toolbar
~~~

I don't see how this can be avoided through the icon rendering.

**Closed by RickStrahl** 2024-11-07 02:37 UTC
