### ISSUE TITLE
Renaming file opens empty file and empty bak files

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1128] opened 2024-08-12 12:12 UTC
- Edit a file
- save it
- rename it in the navigation on the left
- File shows empty and in read mode

![image](https://github.com/user-attachments/assets/353d289b-4dca-4bc5-af3a-2a48f75693de)

- closing and clicking on the renamed file in the navigation tries to load the .bak.md file

![image](https://github.com/user-attachments/assets/7feef124-628d-494c-8ce3-86e844ad06a3)

- clicking on the .. and reopening gives the following, with a different bak file being opened (empty) and the real file being opened with content

![image](https://github.com/user-attachments/assets/ccb7fa3f-9d87-48ed-ad5a-2933d6f69078)

**Comment by internationils** [comment] 2024-08-13 14:07
I was creating and removing files with a script and noticed that some things are not as atomic as I expected in WSL... maybe that is what is happening with the renaming?
```
        # remove it since it is autogenerated
        # does not work immediately, WSL filesystem is too slow to close it
        sleep 0.1
        rm -f $section
```

**Comment by RickStrahl** [comment] 2024-10-22 23:40
Duplicate of #1141. Should be fixed.

**Closed by RickStrahl** 2024-10-22 23:40 UTC
