### ISSUE TITLE
Preview pane disappears if source file extension is .TXT

### ISSUE THREAD

**Issue by TomGreen1943** [RickStrahl/MarkdownMonster#664] opened 2020-05-23 00:59 UTC
When I open a simple file xxx.txt, I can't see the preview pane. The text actually contains markdown, which is just decorated text anyhow.

Somehow the original name of the file causes the problem. 

Similarly a .PRG won't open a preview pane. I was thinking of including some markdown comments.

Is that a configuration option I am missing? Sometimes I would click on the PREVIEW icon and a window would flash open and then close.

Thanks

**Comment by RickStrahl** [comment] 2020-05-23 01:54
That's by design. Files use their native formatting in the editor. PRG files edit as FoxPro files, txt files as text, json files as JSON and so on.

You can change the syntax for a file using the status bar drop down but it's per session. Once you close the file the association is gone.

**Comment by RickStrahl** [comment] 2020-05-23 21:10
Ok so I took a closer look at this and although what I mention above is valid, the behavior isn't quite as expected.

I've added a change by adding a property to the document that holds the active syntax for the document which is updated by the toggle switch and when a new document is assigned to the a document.

You should now be able to open a text document, toggle the syntax to `markdown` and then press F12 to toggle the preview and that should work.

I'm not sure what use case this serves other than perhaps text files that might contain text that looks like Markdown, but I can't see how this would be useful for any sort of code file that has embedded Markdown inside - all the non-markdown text will look like crap in that scenario.

**Comment by RickStrahl** [comment] 2020-05-23 22:10
Here's what this looks like now;

![ChangeDocType](https://user-images.githubusercontent.com/1374013/82741517-72c6c480-9cee-11ea-8714-feb6cb186820.gif)

**Comment by TomGreen1943** [comment] 2020-05-23 23:55
Thanks, Rick. I just think that clicking on the PREVIEW icon should either open the preview pane, or give me a message which would, at the least tell me to do what you are doing, and even better ask me if I want to view it as markdown. Or maybe just open the preview and do it automatically. But doing nothing at all makes no sense.

On another note, I was looking for MARKDOWN ISLANDS in the doc and didn't find it.

**Closed** 2020-05-24 08:40 UTC

**Comment by ProductiveRage** [comment] 2021-03-08 17:46
Just wanted to say thanks, Rick, from myself as well as the OP! For some reason, long ago, I decided to save my blog posts as .txt files even though they were really markdown and I was struggling to get the preview for it in Markdown Monster. I found in the release notes for 1.23 that it was possible to change the syntax in the editor to "markdown" for a .txt file but I couldn't find the option to set syntax in any of the menus - so your video showing that it was in the status bar was invaluable, too!

**Comment by RickStrahl** [comment] 2021-03-08 19:49
@TomGreen1943 

> just think that clicking on the PREVIEW icon should either open the preview pane, 

I disagree, You're opening a **TEXT** file. Text files have no preview that's any different than the input text. There's nothing to preview. it's not Markdown - it's text.

Extensions have meaning in the OS and if you don't use them correctly you will get unexpected results.

**Comment by ProductiveRage** [comment] 2021-03-08 20:54
I agree with Rick (even though I'm someone who is misusing .txt files to contain .md content!) - I was going to rename them all to have .md extensions before I found this issue and the workaround. Tbh, this is just me being a bit lazy and renaming them to something appropriate (ie. "whatever.md") would probably be the better solution (I may well still do that soon, even having found this workaround).
