### ISSUE TITLE
Cannot download posts from Wordpress blog (though I am able to upload posts and 'List Posts')

### ISSUE THREAD

**Issue by Sab73** [RickStrahl/MarkdownMonster#819] opened 2021-07-14 17:08 UTC
I am able to post my md file as a new post into my Worpress blog. That works fine as expected. I am also able to "List Posts" from my Wordpress blog. But when I try to download a blogpost (pressing on the green download button under the title on the list (after I pressed 'List Posts'), an error message appears at the bottom status line of the Weblog Publishing window saying 'Unable to download post'. And then nothing happens.
Since uploading works, listing of blogposts works, I do not know what could be the problem here.

**Comment by RickStrahl** [comment] 2021-07-16 19:12
See it too now. Looks like it has to do with the thumbnail image.

**Comment by RickStrahl** [comment] 2021-07-16 19:35
Take a look at 2.0.0.18 or later - this should be fixed now with the mixed mode parameter for thumbnails.

**Comment by joemclain** [comment] 2021-07-24 17:02
I was having the same problem; I can confirm that it is working now (v 2.0.3).

**Comment by RickStrahl** [comment] 2021-07-24 20:17
Thanks for confirming.

**Closed by RickStrahl** 2021-07-24 20:17 UTC
Labels: bug

**Comment by Sab73** [comment] 2021-07-25 06:03
Thank you. Now I've purchased the full version of MM :)
