### ISSUE TITLE
[Bug] RIght-Click/Context menu fails when using on a laptop with Asus Smart Gesture

### ISSUE THREAD

**Issue by nonplayer** [RickStrahl/MarkdownMonster#778] opened 2021-04-12 20:32 UTC
It's an odd situation that may be hard to replicate, but here's the description. My Asus laptop has a trackpad that allows for multi-finger "clickless" tap actions via the Asus Smart Gesture drivers. The default configuration is a single-finger tap is a single left-click action, while a two-finger tap is a single right-click action.

This works well in every app I've ever used except for, oddly, Markdown Monster. While the single-finger tap works correctly, the two-finger tap flashes the normal right-click context menu but them immediately closes it, too quick to use. A normal right-click action (physical right click using the bottom right corner of the pad) works fine and brings up the sae menu, keeping it open as expected.

At first I thought it may be a driver failure, but even after updating to the latest supported version of Smart Gesture, the issue persists. All other apps that I use - including Atom Notepad++, Explorer, Firefox, Sourcetree, etc - function normally, and only Markdown Monster experiences this "rapid flash" context menu issue when using two-finger tap.

SYSTEM:

- AsusPro P2440UQ Laptop
- Windows 10 x64 v1909
- MM v1.26.10

**Comment by RickStrahl** [comment] 2021-04-13 00:49
Sigh - yes this is a known issue because of the way that the HTML based editor interacts with the WPF based host. Depending on the mouse timing and timing timeouts it's not uncommon for the context menu operation ending up firing multiple times which has the effect of opening and then closing the menu. For most stock mouse scenarios this works fine, but if there's extra software around mouse clicks (like your gesture software most likely) or in some cases virtual machine lag, there can be problems with this.

I have to revisit this but to be frank I've not found a solution to this in the past. I'll look at it again.

**Comment by RickStrahl** [comment] 2021-06-20 18:42
Just as a follow up - the gesture behavio you describe - two-finger click is baked into the base Windows gesture support I believe and that works fine I think. At least I see that working on both of my Dell laptops. The issue is likely more specifically related to additional software that runs on top o the stock drivers. By design these addons will affect the mouse tiimings slightly and I suspect that's what the problem is.

FWIW, for 2.0 Markdown Monster will use the new WebView2 control which will provide more stable HTML event handling. IE has some very oddball mouse handling behavior, so it's possible that the WV will help with this issue.

I can't duplicate this behavior (although I see occasional double activations) in either old or new versions, but once there are beta releases maybe you can take a look and see if this changes anything in the behavior you see on your Asus key software.

**Comment by nonplayer** [comment] 2021-06-25 19:06
Thanks for the update!

**Comment by RickStrahl** [comment] 2021-07-14 16:09
Now that v2 is here (still in late preview) can you give this a try and see if behavior is any better with your custom key manager?

**Comment by nonplayer** [comment] 2021-07-16 20:55
Hi! Since opening this case I have parted ways with that laptop and cannot any longer verify on it. But I can at least verify that it works fine with my Dell XPS laptop, no multi-finger issues at all.

**Comment by RickStrahl** [comment] 2021-07-16 21:18
Thanks for checking. I don't see this on  any of my machines either using the touchpad so this appears to be something specific to the ASUS software.

**Closed by RickStrahl** 2021-07-16 21:18 UTC
Labels: bug
