### ISSUE TITLE
Renaminng renames wrong file

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1119] opened 2024-05-11 09:38 UTC
I right-clicked on the .html file (see the context menu), but the .pdf was still highlighted in the FE. When selecting rename, the .pdf file was selected and ready to rename...

![image](https://github.com/RickStrahl/MarkdownMonster/assets/14021625/5f683b94-4802-4f09-b511-8e87c93f6a50)

![image](https://github.com/RickStrahl/MarkdownMonster/assets/14021625/b943fc42-7c70-4b04-8ecf-61178057dfbc)

**Comment by RickStrahl** [comment] 2024-05-14 00:07
Hmmm... yes this is a regression due to the fact the file the item is no longer selected in the file list.

**Comment by RickStrahl** [comment] 2024-05-14 00:59
Ok that should be fixed. Not just rename that was broken but basically any items that had selection context.

This also fixes the other issue where the menu doesn't show 'in-context' items because previously there was not selected items so those options were not displaying

**Closed** 2024-05-17 03:57 UTC
Labels: bug
