### ISSUE TITLE
Saving encrypted passwords is not working with special characters

### ISSUE THREAD

**Issue by weggetor** [RickStrahl/MarkdownMonster#31] opened 2016-10-27 11:52 UTC
Hi Rick,
I tried to download blog posts from my weblog and I'm getting the following error:
Unable to download posts: Server returned a fault exception: [0] An error occurred while trying to authenticate the user. 
My password has a special character (°) inside. Looking at fiddler I can see that instead of sending this special character MM sends a '?'.

**Comment by RickStrahl** [comment] 2016-10-27 20:18
Is that an extended character code (larger than 255 I assume?)... Password encoding is done with Encoding.ASCII so I suspect that's what the problem is. I suppose we could encrypt with Encoding.Unicode...

Is that really necessary for a password??? :-) I'll have to see what to do about this because the pw encryption happens inside of one of my libraries.

**Comment by RickStrahl** [comment] 2016-10-28 01:09
Ok  fixed by updating base library code in Westwind.Utilities to use UTF-8 for byte conversion. This keeps non extended char passwords intact (ie. raw ascii), but properly encodes passwords with extended characters. You'll need to make sure you update/re-enter your password.

I've updated the Web site download (still shows same 0.57 version however).

**Closed by RickStrahl** 2016-10-28 01:09 UTC
