### ISSUE TITLE
Ghosting outline of the MD frame window across multiple desktops

### ISSUE THREAD

**Issue by joemclain** [RickStrahl/MarkdownMonster#704] opened 2020-09-28 02:56 UTC
Ghosting outline of the MD frame window across multiple desktops, i.e. on desktops on which MD is NOT open. This frame can be sized and moved, which effects MD on its desktop.

Windows Version	10.0.18363 Build 18363

5 desktops, 3 in use

3 monitors

You can see the frame outline on the right side of the attached image. Never seen this before.

-jr-
![image](https://user-images.githubusercontent.com/23348091/94385918-260b5400-00fb-11eb-8a30-ef9a853f13f7.png)

**Comment by RickStrahl** [comment] 2020-09-29 03:26
Wow yeah I can duplicate that. That's quite annoying. The problem here likely is the Window management library that provides the custom Window chrome for MM's main window.

This won't be a quick fix as this likely needs to be fixed at that library level but let me check and see what I can find.

**Comment by RickStrahl** [comment] 2020-09-29 03:59
So it looks like the problem is the `GlowBrush` on the MahApps Metro window. Removing that and replacing it with a simple single line border fixes this problem. There are other issues there in that the active border can't be controlled and there's some lack of contrast on like backgrounds, but that's likely preferable to this behavior :-) For now that'll be the fix.

**Comment by RickStrahl** [comment] 2020-09-30 06:38
This is fixed in 1.24.9.

**Closed by RickStrahl** 2020-09-30 06:38 UTC
Labels: bug

**Comment by joemclain** [comment] 2020-10-01 03:31
Good deal, thanks for looking into is so quickly!

-jr-

________________________________
