### ISSUE TITLE
Feature request: global/project search

### ISSUE THREAD

**Issue by tjrobinson** [RickStrahl/MarkdownMonster#530] opened 2019-06-19 08:10 UTC
I'm liking the new project feature but would like a way of searching all files in that project or folder.

**Comment by RickStrahl** [comment] 2019-06-19 20:09
I think the best way to do that is to open the project folder in the folder browser and you can search from there. Most likely you'd have that folder selected anyway, no?

The only other way I could see that work is to have another tab or a filtered view that shows the project files only. While that could be cool, I also think that would be confusing UI. Most other tools that provide project support (Visual Studio, VS Code) also use the folder structure for working with content rather than showing a 'project view' so I think that's pretty common.

**Comment by tjrobinson** [comment] 2019-06-20 09:58
How do I search across multiple files? I have the folder browser open but can't see any way of searching for a value inside a file, or for a filename in the list.

**Comment by RickStrahl** [comment] 2019-06-22 18:45
There's no support for cross-file searches at this point. What I was referring to was finding files by name.

**Comment by matthewdw** [comment] 2019-07-07 09:09
Duplicate of #540 so you may want to check out Rick's pre-release @tjrobinson!

**Comment by RickStrahl** [comment] 2019-07-07 11:45
Going to close in favor of tracking on #540

**Closed by RickStrahl** 2019-07-07 11:46 UTC
