### ISSUE TITLE
MM hangs when navigating through documents

### ISSUE THREAD

**Issue by realB12** [RickStrahl/MarkdownMonster#951] opened 2022-05-03 08:56 UTC
I am still facing some quirks when navigating through documents by clicking them in the sidebar-tree. It is just happening from time to time and was not able yet to  reproduce the problem on purpose which is the following: 

Suddenly everything start to get strange in a way that the MM editor is no longer responsive for a while and when getting responsive again I can close all open document with the exeception of one that just displays a black screen: 
<img width="526" alt="image" src="https://user-images.githubusercontent.com/3463881/166426886-a7ee02a2-9d5c-401e-b655-2d35a764e1c8.png">
This tab with the black screen cannot be closed by no means. 
After restarting the app, the tab is still there but with the associated doucment open and normally working. 
This happens on various documents. 

It often seems that from time to time the fils and folders in the side-bar are nor longer in sync wiht the object that will be acted upon. So many times the wrong object was moved and one time I have got all a folder deleted wheras the klick was just on a file ....
I am not sure, whether this async-problem is related to the first or not. 

In general - I see still issues when working with the sidebar-tree  1-2 times every hour. 
I hope I will find a way to reproduce and will let you know. In the meantime, maybe you could advice where I should look at more precisely.

Thanks for keeping an eye on this

**Comment by realB12** [comment] 2022-05-03 09:00
Is it possible to trace the click-handler events to find out whether some clicks/events are slipped or "swallowed" or no longer responding?

**Comment by realB12** [comment] 2022-05-03 15:21
Add on: 
When the problem happens the editor shows a black screen whereas the preview renders the (invisible content) ??
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/3463881/166483357-1d2ae1c3-a716-42a6-8980-1babaf5a194b.png">

**Comment by RickStrahl** [comment] 2022-05-03 17:58
Please update to latest version (2.4.14+) - there was some work done on this a couple of weeks back after we had a regression, so it's possible you're looking at the bad batch version.

**Comment by realB12** [comment] 2022-05-04 08:25
ok, I will do and let you know. Thanks

**Comment by realB12** [comment] 2022-05-04 21:04
After updating to Version 2.4.14: Had a full day without crash - seems to work. 
I will close this issue and might come back to it - when the problem should pop up again (which I am confident should not come again - and when yes, when it is just once a day - i can live with that. Anyway - I will give you feedback on this after 2-3 weeks. Should I forget - ask me please. 
Thanks for your support.

**Comment by realB12** [comment] 2022-05-05 05:55
Unfortunately the problem persists: had a crash this morning. 
Found the following that might indicate an problem source: 
When closing MM after hanging, the app is gone from the Desktop but MM process still running/visible in Taskmanager: 
<img width="712" alt="image" src="https://user-images.githubusercontent.com/3463881/166869145-808bc709-f37e-4b7c-aa5c-6e56f838daf5.png">
As you can see there are 2 instance of MM running and MANY WebView instances ??

Can it be that several instances running in the background do not "release" files that will lead to issues when trying to access them from a new launched MM instance? 
Besides normal Antivirus and BackupServices - nothing else is runnig on my machine that could block these files. 

I have the "Use Single Window" flag on
The log is saying the following: 
05.05.2022 07:39:46 - AppDispatcher: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Markdown Monster v2.4.13.2
10.0.19041.1.amd64fre.vb_release.191206-1406 - de-DE - NET 4.8 - 64 bit
de-CH - de-DE    
---
MarkdownMonster
   bei MarkdownMonster.MainWindow.<RefreshTabFromFile>d__79.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei MarkdownMonster.Windows.FolderBrowerSidebar.<TreeViewItem_MouseUpClick>d__59.MoveNext() in C:\projects\MarkdownMonsterCode\MarkdownMonster\Windows\FolderBrowserSidebar\FolderBrowerSidebar.xaml.cs:Zeile 1057.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
System.NullReferenceException
---------------------------



05.05.2022 07:43:49 - Couldn't set file encoding. Assign Utf-8. C:\me\REPO\WIRE\README.md
Der Prozess kann nicht auf die Datei "C:\me\REPO\WIRE\README.md" zugreifen, da sie von einem anderen Prozess verwendet wird.
Markdown Monster v2.4.13.2
10.0.19041.1.amd64fre.vb_release.191206-1406 - de-DE - NET 4.8 - 64 bit
de-CH - de-DE    
---
mscorlib
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   bei MarkdownMonster.mmFileUtils.GetFileEncoding(String srcFile) in C:\projects\MarkdownMonsterCode\MarkdownMonster\_Classes\Utilities\mmFileUtils.cs:Zeile 343.
   bei MarkdownMonster.MarkdownDocument.GetFileEncoding(String filename) in C:\projects\MarkdownMonsterCode\MarkdownMonster\_Classes\MarkdownDocument.cs:Zeile 1099.
System.IO.IOException
---------------------------



05.05.2022 07:43:49 - Snippets::AddIn::OnWindowLoaded Error: Der angeforderte Wert "2D" konnte nicht gefunden werden.

**Comment by realB12** [comment] 2022-05-05 06:17
After restarting my PC and launching MM I have only 
<img width="835" alt="image" src="https://user-images.githubusercontent.com/3463881/166870480-6250e486-cf1d-4221-95c0-955823904256.png">
And when opening a file: 
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/3463881/166871337-d1a1364b-04aa-43cf-81c4-c75f8e2e4fc1.png">
Are the many WebView instances normal? 

When closing MM normally, nothing "hangs" in the Taskmanager. 

It seems to me, that after the crash,  MM and WebView instances "hang" in the Background and might block ressources - can this be?

**Comment by realB12** [comment] 2022-05-05 08:50
Finally I can reproduce at least one case with a very simple example: 

## Setup
Have two files A.md and B.md in the same folder with following content

**A.md**
```markdown
# A.md
[Link to B.md](B.md)
```

**B.md**
```markdown
# B.md
[Link to A.md](A.md)
```

## Fail01
MM closed, nothing running in the background

1.  **Explorer**: clicking on `/TestWire/A.md` file
    
    -> file opens in MM (with navigation tree from last MM-usage which is not related to the `/TestWire/A.md` file --> another issue??)
    
2. Right-Click into Editor Window and selecting "Show in the Folder Browser"    

3. In the Folder Browser open-click `SUB/B.md` 

    -> B.md opens 

4. In the **Preview-Window** mouse-click on the `"Go to A"`-Link --> **MM-Ediotr is freezing, Tabs behave strange (black window) and MM cannot be closed --> have to force-close it with Task-Manager**. 


## Hints
1. The Freeze is **only happening when clicking Links in the Preview-Window** but does NOT happen when `Ctrl+Click` the Link in the Editor window!!

2. Problem persists after rebooting Windows with nothing else running.

3. `Autosave` and `Use in Same Window`-settings have no effect

**Comment by RickStrahl** [comment] 2022-05-12 23:31
This is a duplicate of another issue (that I can't find right now). There is a bug in the WebView2 control that's the cause of this and there's currently no work around. I filed a bug in the WebView support forum but there's no word on the fix.

Use the links in the editor to navigate to other documents for now.

**Closed by RickStrahl** 2022-05-12 23:31 UTC

**Comment by realB12** [comment] 2022-05-15 06:25
Hi Rick, 
I is second nature that we have bugs in other components we are using. So we have to find ways to get around it. 
Since we have switched to WebView  MM is crashing several times a day for THIS issue and for other drag-drop related issues. Several times a day I have to restart MM because the FileTree got asyced with mouse clicks (clicking file A, opens file B). So it looks to me - not being a Pro myself - that there is a general problem with event-handling where events are losing context (addressing the wrong targets). 
For me, MM makes 1-2 hours a day intensive working and I do presentations with it. When this instability cannot be fixed I have to switch to another products (at least for presentations). 
I do not expect that those issues are fixed immediately. But I do not accept waiting for Microsoft to come up with a solution. I do expect a work-around or to go back to the old stuff that worked. 
Your tool is stealing me a considerable amount of time every day! I can deal with it, as long as I have faith that somebody is working on theses issues.
