### ISSUE TITLE
Spell Check Context in Wrong Location

### ISSUE THREAD

**Issue by thnk2wn** [RickStrahl/MarkdownMonster#583] opened 2019-10-09 18:56 UTC
Markdown Monster Version 1.19.9

Spell check underlines seem to be in the wrong location in cases:

<img width="383" alt="2019-10-09_14-53-05" src="https://user-images.githubusercontent.com/120529/66511328-bc86d580-eaa4-11e9-8ece-903ad3b11d23.png">

Here I was typing a longer paragraph with no line breaks where wrapping was happening.

**Comment by RickStrahl** [comment] 2019-10-09 22:28
Did this clean up when you scrolled up or down a little?

The spell checking logic doesn't run continually it's on a timed background worker which sometimes doesn't get scheduled to update (due to browser threading issues). In most those cases scrolling up or down, or worst case scrolling the page, will bring it back into sync.

That said, I haven't seen this in quite a while. You see this often or is this a rare occurrance? If you have repro scenario that would also be useful.

**Comment by thnk2wn** [comment] 2019-10-10 01:51
It stayed when I scrolled down but eventually went away after I started changing that paragraph more.

I saw it once before briefly while typing but it quickly was fixed. In this case it persisted for some time until making further edits to the section. 

I can see if it's still there later / persistent and whether I can provide any reliable repro later.

**Comment by RickStrahl** [comment] 2019-10-11 21:48
I have looked at this a few times, but unfortunately don't have a good way to fix it. If it goes off the rails, the quickest way to 'fix' it is to toggle spell check on and off (Alt-E-S).

I think the problem is that if the document is busy with other things the spell check update loop on occasion is skipped. Then if the document isn't dirty it doesn't refresh until you type again. However, if the document is idle that should catch up. 

I haven't seen it out of sync in a long while though in my own setup here but I have a fast machine and that certainly helps with the skipped cycles.

**Comment by RickStrahl** [comment] 2019-10-12 22:50
Spent a little time tightening up the spell checking code. There are some additional things that happen for enter and backspace/del which can affect the positioning and reduced the refresh timeout quite a bit for the spell checker. 

All of this should help make the spell checker not lag as much as it did before and so reduce the likelyhood of getting out of sync.  

The one caveat here is that this may have an impact on editor performance. Still playing with the right balance but on my (admittedly fast) machine I don't really see any impact of the much more frequent updates.

Check with the next update (1.19.9.3 or later) to see the changes.

Going to close this - feel free to re-open if you run into the same issues or if you come up with a repro scenario.

**Closed by RickStrahl** 2019-10-12 22:50 UTC
