### ISSUE TITLE
Error when posting via Weblog API

### ISSUE THREAD

**Issue by weggetor** [RickStrahl/MarkdownMonster#7] opened 2016-06-09 09:03 UTC
![2016-06-09_10-56-41](https://cloud.githubusercontent.com/assets/5718742/15924280/94ed1ac6-2e31-11e6-818a-6cb2be1cc066.png)
09.06.2016 10:56:11 - Server returned a fault exception: [0] request contains int value where string expected [request : parameter 1]
---
````
CookComputing.XmlRpcV2
   bei CookComputing.XmlRpc.XmlRpcResponseDeserializer.DeserializeFault(IEnumerator`1 iter)
   bei CookComputing.XmlRpc.XmlRpcResponseDeserializer.DeserializeResponse(XmlReader rdr, Type returnType)
   bei CookComputing.XmlRpc.XmlRpcClientProtocol.ReadResponse(XmlRpcRequest req, WebResponse webResp, Stream respStm)
   bei CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke(Object clientObj, MethodInfo mi, Object[] parameters)
   bei XmlRpcProxy1e78ecc9-3c84-4ab5-9d36-d10a88f47fe9.NewMediaObject(Int32 blogId, String username, String password, XmlRpcMediaObject mediaObject)
   bei JoeBlogs.MetaWeblogWrapper.NewMediaObject(MediaObject mediaObject)
   bei WeblogAddin.WebLogAddin.SendImages(String html, String filename, MetaWeblogWrapper wrapper)
   bei WeblogAddin.WebLogAddin.SendPost(WeblogTypes type)
   bei WeblogAddin.WebLogForm.<>c__DisplayClass7_0.<ButtonPostBlog_Click>b__0()
   bei System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei WeblogAddin.WebLogForm.<ButtonPostBlog_Click>d__7.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
````

**Comment by RickStrahl** [comment] 2016-06-09 17:29
Ah yes, that's a problem with the MetaWebLogApi which doesn't have a fixed type definition for the post ID. The client library I'm using is using int for the post ID. I played around with switching to string, but then other blogs were breaking. I have to take a look and see how this could be resolved with a non-specific type.

What engine are you publishing to?

**Comment by RickStrahl** [comment] 2016-06-09 17:47
Hmmm... also noticing the icons are missing on the buttons in your screen shot. Are the icons showing up in your toolbar?

**Comment by weggetor** [comment] 2016-06-10 07:01
Hi Rick. Icons in the toolbar are OK: 
![2016-06-10_08-55-12](https://cloud.githubusercontent.com/assets/5718742/15956537/755fdf8c-2ee9-11e6-96bc-ba67ad90f27e.png)
Publishing engine... It's Peter Donkers Blog module for DotNetNuke (see: https://github.com/DNN-Connect/DNN-Blog)

**Comment by RickStrahl** [comment] 2016-06-10 08:53
Looks like they are not using MetaWebLogApi or WordPress but blogMl which is yet another format that's currently not supported.

I'm still looking at finding a library that can handle different engines (which apparently doesn't exist). I may end up writing a library for this stuff but at this point that's not high on the list unfortunately since the most common MetaWebLogApi and Wordpress work.

**Comment by weggetor** [comment] 2016-06-10 09:04
Hi Rick. Don't think so because it could be used with windows Live Writer (see: https://github.com/DNN-Connect/DNN-Blog/blob/master/_Documentation/Manual.md#wlw)

**Comment by RickStrahl** [comment] 2016-06-10 09:32
Yes, but Live Writer supports BlogMl if I recall.

**Comment by weggetor** [comment] 2016-06-10 10:01
I asked Peter, he is using MetaWebLog API (see:https://github.com/DNN-Connect/DNN-Blog/tree/master/Components/Services/WLW). He implemented BlogML too but only for importing / exporting blog posts.

**Comment by RickStrahl** [comment] 2016-06-10 17:35
Thanks Torsten. I'll look at it and see if I can figure out a way so post uploads can work with string and int postids. So much for a spec that's clear :-) Heck there's no real spec that I can even find anywhere just implementations which vary between the two. 

You don't by chance have the ability to set up a test account in your DNN setup?

**Comment by weggetor** [comment] 2016-06-10 19:16
Hi Rick, I set up a demo DNN website with blog module on http://demo.indisoftware.de. The MetaWeblog URL is: http://demo.indisoftware.de/DesktopModules/Blog/BlogPost.ashx?portalid=0&tabid=59&moduleid=414 , user / pw is horst / dnnhorst . Please let me know when you finished testing so that  I can delete this instance

**Comment by RickStrahl** [comment] 2016-06-10 19:22
Awesome - thanks Torsten - appreciate it. One less thing to set up for me...
Aloha.

**Comment by RickStrahl** [comment] 2016-06-10 23:05
... and we have lift off :-)

So the issue was indeed the silly typing of the blog and post ids. I changed the API to use `object` and default to strings now, which works with the three things I've tested with so far:

* My blog (MOST important of course :-) Custom MetaWebLog API)
* WordPress on Wordpress.com
* DNN-Connect (MetaWebLogAPI)

The wrapper lib I've been using was using ints for everything and while that's legal, it is likely to cause problems because most MetaWebLogApi implementations either use strings or object with an expectation of strings.

Can you give it a try with v0.30 (just uploaded). It worked for this:
http://demo.indisoftware.de/Home/Post/192

Thanks for making the link avalaible. If you don't mind leave it running for a little while longer. There are a few more things to figure out. You may have to configure the Blog ID explicitly (it defaults to 1 which is probably fine).

**Comment by weggetor** [comment] 2016-06-11 19:59
Hi Rick, wanted to update but could not find version 0.30 (neither me not your software). 
![2016-06-11_21-57-59](https://cloud.githubusercontent.com/assets/5718742/15987178/bb80f438-301f-11e6-9bf2-4fd33e2561a9.png)
![2016-06-11_21-58-18](https://cloud.githubusercontent.com/assets/5718742/15987179/bdeaf958-301f-11e6-83c2-86324680d36c.png)

**Comment by RickStrahl** [comment] 2016-06-12 01:47
Not sure why that wouldn't work. From what I can tell the download links are all working. Just tried updating from test machine that's still running an older version and it seems to work.

FWIW, you can also grab it from the download site:.

http://markdownmonster.west-wind.com/download.aspx

Does it seem like the download is working (ie. some delay while the file is downloaded and then working?

**Comment by weggetor** [comment] 2016-06-12 09:25
Hi Rick,
no the error comes immediatly. Seems that it looks on the wrong URL ? I have had a look with fiddler in your xml containing the latest version info. There was no file URL, so this may be the reason ?

**Comment by weggetor** [comment] 2016-06-12 09:30
Another thing: I tried now the version 0.30 and it works fine with DNN blog. But only if I give it a blog Url (=1) and a post ID of an existing post. Do I have to create a post first on the website and then fill it with Markdown Monster ? If I leave the PostId field empty I get an error:

**Comment by weggetor** [comment] 2016-06-12 09:49
And another suggestion: In DNN Blog it is possible to add a "Post image" (shown in the list of posts as teaser image and in the post details as header image). Would be nice to define this with MM too because at the moment this image is deleted every time I update the post from MM

**Comment by RickStrahl** [comment] 2016-06-12 17:11
Torsten - The blog id is something I'll have to figure out yet - for now you have to set it to match your blog id (which appears is a static 1). I think most sites don't actually use the blog id - the end point determines where the post is going usually.

I can see the same error - you are showing. Some regression with the changes I made.

**Comment by RickStrahl** [comment] 2016-06-12 18:05
Ok, as expected, logic error introduced by the type change in the add-in. Fixed now - you should now be able to post new entries and update again.

**Comment by weggetor** [comment] 2016-06-12 21:30
Nope , update does not work for me. See attached Fiddler file
[2_Full.txt](https://github.com/RickStrahl/MarkdownMonster/files/310992/2_Full.txt)

**Comment by RickStrahl** [comment] 2016-06-12 22:45
Hmmm... it's sending you to the wrong url for sure. Which means it's probably a config settings that not set correctly. Can you check the config file and see if you have a `InstallerDownloadUrl` reference in your settings and remove that key? It shouldn't be there (previous bug). Most likely that's what's pointing at the wrong location.

Goto Tools | Settings then look for that key.

The value shouldn't be in the config and if it is it should be pointing to: `http://west-wind.com/files/MarkdownMonsterSetup.exe`

**Comment by weggetor** [comment] 2016-06-13 07:49
It's not in there, so maybe the self-healing did the job. Awaiting the next update to check this

**Comment by RickStrahl** [comment] 2016-06-13 07:58
So does your posting work with a new post now?

**Comment by weggetor** [comment] 2016-06-13 08:04
Yes works perfect! At the moment I'm dealing with the code highlighter themes (DNN Blog is working with SyntaxHighlighter and I need to make it work with your highlight.pack.js - but this is not your business ;-) ). Did you have a thought about the "Post image" - thing ?

**Comment by RickStrahl** [comment] 2016-06-13 17:31
I mentioned it above a few responses back. But... can you break out each issue into a separate thread? It'll be easier to track this way.

I'm closing this issue since the posting is working for you now.

**Closed by RickStrahl** 2016-06-13 17:31 UTC
